# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads'
    user_pfp: '%kernel.project_dir%/public/uploads/profile_picture'
    locale: 'en'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    Twilio\Rest\Client:
        arguments:
            - '%env(AC5f2f3bfeb5b06afb41108004bdac2604)%'
            - '%env(5350aec9663d774c6aa215abb44f7a7d)%'
    Symfony\Component\Mailer\Mailer:
        class: Symfony\Component\Mailer\Mailer
        arguments:
            - '@Symfony\Component\Mailer\Transport'
            - '@Symfony\Component\Mime\MimeTypes'
    App\Service\TwilioSmsService:
        arguments:
            $accountSid: '%env(TWILIO_ACCOUNT_SID)%'
            $authToken: '%env(TWILIO_AUTH_TOKEN)%'
            $twilioPhoneNumber: '%env(TWILIO_PHONE_NUMBER)%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
